### ISSUE TITLE
Overall deliverables project plan

### ISSUE THREAD

**Issue by hkLolgast** [hkLolgast/DSE_SCULPTUR#5]
These are all of the overall deliverables which need to be done
- [x] DSE work-flow diagram
  - [x] Propulsion
  - [x] Aerodynamics
  - [x] Materials and structures
  - [x] Performance group
- [x] DSE work break-down structure
  - [x] Propulsion
  - [x] Aerodynamics
  - [x] Materials and structures
  - [x] Performance group
- [x] DSE Gantt chart
- [x] DSE team organization/HR allocation

- [x] Write up
- [x] Proofreading

**Comment by hkLolgast** [comment]
Report was handed in
